### ISSUE TITLE
Possible memory leak when adding/removing lots of entities.

### ISSUE THREAD

**Issue by junkdog** [libgdx/ashley#129]
While running some benchmarks against ashley-1.3.3, the JVM throws an OutOfMemoryError. 

```
# VM invoker: /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java                                                                                                                                                                               [1273/1952]
# VM options: <none>
# Warmup: 5 iterations, 1 s each
# Measurement: 3 iterations, 10 s each
# Timeout: 60 s per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Benchmark: com.github.esfbench.ashley.InsertRemoveBenchmark.insert_remove
# Parameters: (entityCount = 16384)

# Run progress: 50.00% complete, ETA 00:03:44
# Fork: 1 of 1
# Warmup Iteration   1: 108.858 ops/s
# Warmup Iteration   2: 94.576 ops/s
# Warmup Iteration   3: 159.222 ops/s
# Warmup Iteration   4: 137.726 ops/s
# Warmup Iteration   5: 14.095 ops/s
Iteration   1: 54.116 ops/s
Iteration   2: <failure>

java.lang.OutOfMemoryError: Java heap space
        at com.badlogic.gdx.utils.LongMap.resize(LongMap.java:522)
        at com.badlogic.gdx.utils.LongMap.put(LongMap.java:148)
        at com.badlogic.ashley.core.Engine.addEntityInternal(Engine.java:333)
        at com.badlogic.ashley.core.Engine.addEntity(Engine.java:121)
        at com.github.esfbench.ashley.system.EntityManglerSystem.createEntity(EntityManglerSystem.java:136)
        at com.github.esfbench.ashley.system.EntityManglerSystem.update(EntityManglerSystem.java:118)
        at com.badlogic.ashley.core.Engine.update(Engine.java:264)
        at com.github.esfbench.ashley.InsertRemoveBenchmark.insert_remove(InsertRemoveBenchmark.java:55)
        at com.github.esfbench.ashley.generated.InsertRemoveBenchmark_insert_remove.insert_remove_thrpt_jmhStub(InsertRemoveBenchmark_insert_remove.java:107)
        at com.github.esfbench.ashley.generated.InsertRemoveBenchmark_insert_remove.insert_remove_Throughput(InsertRemoveBenchmark_insert_remove.java:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openjdk.jmh.runner.LoopBenchmarkHandler$BenchmarkTask.call(LoopBenchmarkHandler.java:198)
        at org.openjdk.jmh.runner.LoopBenchmarkHandler$BenchmarkTask.call(LoopBenchmarkHandler.java:180)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```

When running the same benchmark against 1.3.2, the process hangs and has to be forcibly killed (might be a problem with JMH, but I haven't encountered it before). 1.3.1 had the stackoverflow bug, so I'm unsure whether this particular problem existed before 1.3.1 or not.

I can probably have a look at it during the weekend, unless anyone has an idea what's going on?

[EntityManglerSystem.java:136](https://github.com/junkdog/entity-system-benchmarks/blob/31caa5d0e61472338c005843a3d6aa5da961cc8f/ashley-1.3.1/src/main/java/com/github/esfbench/ashley/system/EntityManglerSystem.java#L136)

**Comment by siondream** [comment]
Could you please keep track of how many entities are in the system while the test runs? I'm removing the ids from the `LongMap` when an entity is removed. So it could be something in the testing code that ends up adding more entities than it removes.

**Comment by junkdog** [comment]
I was accidentally [deleting the same entity multiple times](https://github.com/junkdog/entity-system-benchmarks/blob/31caa5d0e61472338c005843a3d6aa5da961cc8f/ashley-1.3.1/src/main/java/com/github/esfbench/ashley/system/EntityManglerSystem.java#L112) (thanks to @piotr-j for noticing), in effect creating entities at a much higher rate than deleting them. 
Bad :dog: .
